#!/bin/bash

#SBATCH -J shallow
#SBATCH -o shallow_%j.out
#SBATCH -e shallow_%j.err
#SBATCH --nodes=6
#SBATCH --ntasks=96
#SBATCH --tasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --get-user-env
#SBATCH -t 00:05:00
#SBATCH --mem-per-cpu=1000
#SBATCH --partition=compute

source /etc/profile.d/modules.sh
#module load openmpi-4.0.0
cd $HOME/shallow-water
mpirun -np 81 src/lshallow tests.lua dam 1000 9 9
